# Generated by Django 3.1.3 on 2021-01-06 03:50

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='', max_length=191)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('location', models.CharField(default='', max_length=191)),
                ('deviceId', models.CharField(default='', max_length=191)),
                ('deviceType', models.CharField(default='', max_length=100)),
                ('timezone', models.CharField(default='', max_length=191)),
                ('created_date', models.DateField(auto_now=True, null=True)),
                ('onOffNotification', models.IntegerField(default=1)),
                ('role', models.IntegerField(default=0)),
                ('image', models.CharField(default='', max_length=191)),
                ('lastUpdated', models.DateTimeField(null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_otp_verified', models.IntegerField(default=0)),
                ('total_friends', models.IntegerField(default=0)),
                ('accept_Chats_from', models.IntegerField(default=0)),
                ('read_receipt', models.IntegerField(default=0)),
                ('add_phone_contact', models.IntegerField(default=0)),
                ('friend_request', models.IntegerField(default=1)),
                ('new_messages', models.IntegerField(default=1)),
                ('new_comments', models.IntegerField(default=1)),
                ('from_us', models.IntegerField(default=1)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('firebase_token', models.TextField(default='', max_length=255)),
                ('active_status', models.IntegerField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'auth_user',
                'verbose_name_plural': 'auth_users',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.IntegerField(default=0)),
                ('is_file', models.IntegerField(default=0)),
                ('sender_status', models.IntegerField(default=1)),
                ('receiver_status', models.IntegerField(default=1)),
                ('thumbnail', models.TextField(default='', verbose_name='thumbnail')),
                ('duration', models.CharField(default='', max_length=200)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ('-timestamp',),
            },
        ),
    ]
